import 'package:args/args.dart';

/// A utility class containing constants and CLI options for the AppFlow CLI tool.
class AppFlowConstants {
  /// CLI argument parser with defined options and flags.
  ///
  /// Includes:
  /// - config: path to the config file (default: 'app_flow_cli.yaml')
  /// - add: module/feature to add (default: '')
  /// - overwrite: flag to allow overwriting existing files
  /// - clean: flag to remove previously generated files/folders
  /// - help: flag to display usage information
  static dynamic helpOptions = ArgParser()
    ..addOption(
      'config',
      abbr: 'c',
      help: 'Path to config YAML file',
    )
    ..addOption(
      'add',
      help: '--add <module> to the structure',
      defaultsTo: 'structure',
    )
    ..addFlag(
      'overwrite',
      abbr: 'o',
      help: 'Overwrite existing files',
      defaultsTo: false,
    )
    ..addFlag(
      'clean',
      help: 'Remove all generated files/folders created by appflow',
    )
    ..addFlag(
      'status',
      help: 'Show all files and folders generated by AppFlow',
    )
    ..addOption(
      'make-route',
      help: 'Automatically generates routes for new pages in --make-route <page> file',
    )
    ..addOption(
      'rm',
      help: 'Removes a module or feature from the structure',
    )
    ..addFlag(
      'help',
      help: 'Show usage information',
      negatable: false,
    );

  /// Key used to represent the structure section in the config file.
  static String structure = 'structure';

  /// Key used to represent comments in the config file.
  static String comments = 'comments';

  /// List of folders to create during the initial setup.
  static List<String> additionFolders = [
    'assets/',
    'lib/src/features/',
  ];

  static String addOption = 'add';
  static String configOption = 'config';
  static String overwriteOption = 'overwrite';
  static String pageOption = 'page';
  static String removeOption = 'rm';
  static String makeRouteOption = 'make-route';

  static String version = '1.0.2+';
  static String trackingFileName = '.appflow_generated.json';

  static String screens_dir = 'lib/screens';
  static String appflowImports = '// <appflow-imports>';
  static String appflowConstants = '// <appflow-constants>';

  static String appflowRouteRegex = "// <appflow-start:route>(.|\n)*?//<appflow-end:route>";
}